services:
  postgres:
    image: postgres:16
    container_name: music_db
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
